#ifndef COLORSCALE_GLOBAL_H
#define COLORSCALE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COLORSCALE_LIBRARY)
#  define COLORSCALESHARED_EXPORT Q_DECL_EXPORT
#else
#  define COLORSCALESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COLORSCALE_GLOBAL_H
