#ifndef BOTTOMHEATING_GLOBAL_H
#define BOTTOMHEATING_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BOTTOMHEATING_LIBRARY)
#  define BOTTOMHEATINGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BOTTOMHEATINGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BOTTOMHEATING_GLOBAL_H
