#ifndef TRIANGLEFEMTOOLS_GLOBAL_H
#define TRIANGLEFEMTOOLS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TRIANGLEFEMTOOLS_LIBRARY)
#  define TRIANGLEFEMTOOLSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TRIANGLEFEMTOOLSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TRIANGLEFEMTOOLS_GLOBAL_H
