#ifndef OPENGLPAINTER_GLOBAL_H
#define OPENGLPAINTER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(OPENGLPAINTER_LIBRARY)
#  define OPENGLPAINTERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define OPENGLPAINTERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // OPENGLPAINTER_GLOBAL_H
