#ifndef SIDEHEATING_GLOBAL_H
#define SIDEHEATING_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SIDEHEATING_LIBRARY)
#  define SIDEHEATINGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SIDEHEATINGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SIDEHEATING_GLOBAL_H
